# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/KCU116_Rev1.0_XDC_20230407_for_ad9164.xdc

# Block Designs: bd/Signal_Souce_Control_BD/Signal_Souce_Control_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD || ORIG_REF_NAME==Signal_Souce_Control_BD} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_microblaze_0_0/Signal_Souce_Control_BD_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_microblaze_0_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_microblaze_0_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_uartlite_0_0/Signal_Souce_Control_BD_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_axi_uartlite_0_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_quad_spi_0_0/Signal_Souce_Control_BD_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_axi_quad_spi_0_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_axi_gpio_0_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_intc_0_0/Signal_Souce_Control_BD_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_axi_intc_0_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_axi_intc_0_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_xlconcat_0_0/Signal_Souce_Control_BD_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_xlconcat_0_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_xlconcat_0_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_dlmb_v10_0/Signal_Souce_Control_BD_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_dlmb_v10_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_dlmb_v10_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_ilmb_v10_0/Signal_Souce_Control_BD_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_ilmb_v10_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_ilmb_v10_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_dlmb_bram_if_cntlr_0/Signal_Souce_Control_BD_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_ilmb_bram_if_cntlr_0/Signal_Souce_Control_BD_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_lmb_bram_0/Signal_Souce_Control_BD_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_lmb_bram_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_lmb_bram_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_mdm_1_0/Signal_Souce_Control_BD_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_mdm_1_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_mdm_1_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_clk_wiz_1_0/Signal_Souce_Control_BD_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_clk_wiz_1_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_rst_clk_wiz_1_100M_0/Signal_Souce_Control_BD_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_xbar_0/Signal_Souce_Control_BD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_xbar_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_xbar_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_1_0/Signal_Souce_Control_BD_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_axi_gpio_1_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_microblaze_0_axi_periph_0/Signal_Souce_Control_BD_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Signal_Souce_Control_BD_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Signal_Souce_Control_BD_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/Signal_Souce_Control_BD_ooc.xdc
