# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.srcs/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0.xci
# IP: The module: 'Signal_Souce_Control_BD_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Signal_Souce_Control_BD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Signal_Souce_Control_BD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Signal_Souce_Control_BD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.srcs/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0.xci
# IP: The module: 'Signal_Souce_Control_BD_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Signal_Souce_Control_BD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Signal_Souce_Control_BD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/DMTS/MOLIT_Shoe_Schaner/Development/FPGA/Signal Source Control/Vivado/Signal_Souce_Control/Signal_Souce_Control.gen/sources_1/bd/Signal_Souce_Control_BD/ip/Signal_Souce_Control_BD_axi_gpio_0_0/Signal_Souce_Control_BD_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Signal_Souce_Control_BD_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
